version: '3.8'
services:
  client:
    build: ./chat-app
    volumes:
      - ./chat-app:/app
    ports:
      - "8080:8080"
    depends_on:
      - server
  server:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - "3000:3000"
